### ISSUE TITLE
[Question] Cold start times

### ISSUE THREAD

**Issue by ShantanuNair** [tensorfuse/tensorfuse-examples#1]
Would it be possible to have some data on what recent cold start times are for each example - perhaps rerun after platform changes, with cold start timings updated? This would at least give us some idea of cold start times if we're considering switching from providers such as Modal/Beam/etc where it's super easy to try something out and get a gauge on how it performs. Just my 2c :)

**Comment by agamjn** [comment]
@ShantanuNair 
Valid suggestion! Sure, we will include the cold starts time as well. 
For now, there are 3 stages with GPU cold start times:

Stage 1: Provisioning a machine
Stage 2: Loading the Docker image
Stage 3: Loading the model into GPU VRAM (for GPU workloads)


Stage 1 it entirely depends upon the cloud provider and currently its around 45secs
Stage2, we have cold starts of around 20 secs for a 15 GB image
Stage 3 again depends upon the size of the model and it takes around 20 secs to load a 16gb model into GPU. 

So on warm node, cold starts are around ~40secs for a 15-20GB image
